name: Java Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Select an operating system

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Maven
        run: sudo apt-get install maven -y

      - name: Clone Project
        run: git clone https://github.com/bilobran/bilobrantestapp.git

      - name: Change Directory
        run: cd copyolder

      - name: Download Dependencies and Build Project
        run: |
          mvn clean install

      - name: Run Unit Tests
        run: mvn test
