name: Java Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Select an operating system

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get install maven -y

      - name: Clone Project
        run: git clone https://github.com/yourusername/yourproject.git

      - name: Change Directory
        run: cd yourproject

      - name: Download Dependencies and Build Project
        run: |
          mvn clean install

      - name: Run Unit Tests
        run: mvn test
